# Links para repos:
# Github: https://github.com/omateusp/Workshop-CI-Entrega-02
# Gitlab: https://gitlab.com/omateusp/Workshop-CI-Entrega-02
# Docker Hub frontend: https://hub.docker.com/repository/docker/omateusp/workshop-ci-entrega-02-frontend
# Docker Hub backend: https://hub.docker.com/repository/docker/omateusp/workshop-ci-entrega-02-backend
stages:
  - build
  - test

image: docker:latest

services:
  - docker:dind

# Criando duas tags para não perder versões anteriores.
variables:
  FRONTEND_IMAGE_TAG: ${USER}/${PROJECT_NAME}-frontend:$CI_COMMIT_SHA
  FRONTEND_IMAGE_LATEST: ${USER}/${PROJECT_NAME}-frontend:latest
  BACKEND_IMAGE_TAG: ${USER}/${PROJECT_NAME}-backend:$CI_COMMIT_SHA
  BACKEND_IMAGE_LATEST: ${USER}/${PROJECT_NAME}-backend:latest  

backend_build:
  stage: build
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER" --password-stdin
    - docker pull $BACKEND_IMAGE_LATEST || true
  script:
    - docker build --cache-from $BACKEND_IMAGE_LATEST -t $BACKEND_IMAGE_TAG -t $BACKEND_IMAGE_LATEST ./backend/
    - docker push $BACKEND_IMAGE_TAG
    - docker push $BACKEND_IMAGE_LATEST

frontend_build:
  stage: build
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER" --password-stdin
    - docker pull $FRONTEND_IMAGE_LATEST || true
  script:
    - docker build --cache-from $FRONTEND_IMAGE_LATEST -t $FRONTEND_IMAGE_TAG -t $FRONTEND_IMAGE_LATEST ./frontend/
    - docker push $FRONTEND_IMAGE_TAG
    - docker push $FRONTEND_IMAGE_LATEST

backend_test:
  stage: test
  before_script:
    - docker pull $BACKEND_IMAGE_TAG
  script:
    - docker run --entrypoint "npm" "$BACKEND_IMAGE_TAG" run unittest


frontend_test:
  stage: test
  before_script:
    - docker pull $FRONTEND_IMAGE_TAG
  script:
    - docker run --entrypoint "npm" "$FRONTEND_IMAGE_TAG" run test
